### ISSUE TITLE
Action run failure, process completed with exit code 3.

### ISSUE THREAD

**Issue by fabiocaccamo** [browniebroke/pre-commit-autoupdate-action#1]
Hi Bruno, 
thank you for this great action.

I'm using `pre-commit-autoupdate-action` since few weeks and everything worked fine, but now the action fails (`Process completed with exit code 3.`) on all the repositories where I'm using it:

<img width="493" alt="pre-commit-autoupdate-action" src="https://user-images.githubusercontent.com/1035294/205442971-d31514d4-c6dd-46ac-b87b-c85487327c6a.png">

Here the run log:

<img width="1059" alt="Screenshot 2022-12-03 at 14 25 23" src="https://user-images.githubusercontent.com/1035294/205443053-be16afcd-2d8a-4f59-bc5a-44d10127bf42.png">

**Comment by browniebroke** [comment]
Hey 👋🏻 

It looks like it's failing while running pre-commit, when it's setting up the environment for black. The error says that there is no Python 3.8 interpreter in the runner.

Looking at one of your repos, I can see the config for the black hook [requires Python 3.8](https://github.com/fabiocaccamo/django-admin-interface/blob/f4df5c528992b2514cf22fc5da911206d819f760/.pre-commit-config.yaml#L9) ([docs](https://pre-commit.com/#overriding-language-version)), however, you run the action [with Python 3.11](https://github.com/fabiocaccamo/django-admin-interface/blob/f4df5c528992b2514cf22fc5da911206d819f760/.github/workflows/pre-commit-autoupdate.yml#L17).

Do you have specific reason to run black under Python 3.8? As far as I know, it can be confugured to reformat Python code for a different version, using the `target-version` option.

**Comment by fabiocaccamo** [comment]
You are right, I was looking in the wrong place, than you for the help and sorry for the noise.

**Comment by browniebroke** [comment]
No worries! 

PS: thanks for your work on your libraries, I used `django-admin-interface` at a previous job and it worked great 😄 Glad one of little project can help you back 🎉

**Comment by fabiocaccamo** [comment]
It's a plaisure! 
I remember you also contributed to `django-admin-interface`, double thanks!
